

# Стикеры (гарантированная отправка)

STICKERS = {
    # Старт
    "start": [
        "CAACAgIAAxkBAAP7aRgMvEO0UTPPG0PxKVDexPCZy98AApVQAAJ4cMFJgqJ1IfE_lBg2BA",
        "CAACAgIAAxkBAAPuaRgLP26VtetKzKsHPMK3COsOqVwAAnpMAALZi8BJMK6P8aVrmuU2BA"
    ],
    
    # Мои ссылки
    "my_links": [
        "CAACAgIAAxkBAAIBAAFpGA2KVB7jalARxzxhUycdZizvBgACMFQAApdrwEldJIx3iORlZTYE",
        "CAACAgIAAxkBAAPwaRgLVcnSTOcUMKv-u4Ey5P7Ex5EAAoVGAAIIasFJvCHntQYr_xc2BA",
        "CAACAgIAAxkBAAIBBWkYDipxFulimrVaf_vA5JQy3umMAAIOVAACzhPASRVVua8FEG0pNgQ",
        "CAACAgIAAxkBAAIBB2kYDkgak1VauWlU1Jb1Sy5V2So-AALGTwACXPLASSsNgcr1SifuNgQ"
    ],
    
    # Статистика
    "stats": [
        "CAACAgIAAxkBAAIBAAFpGA2KVB7jalARxzxhUycdZizvBgACMFQAApdrwEldJIx3iORlZTYE",
        "CAACAgIAAxkBAAIBCWkYDpL-X6rS8pZ7A31_DiE-AoiwAALnSQAC7AnBSVKbZqekRizDNgQ",
        "CAACAgIAAxkBAAIBC2kYDpqdQ8PceEdz9_140q5rS_FhAAK4UQACMRjASY_dsdrpYbRHNgQ"
    ],
    
    # Топ участников
    "top": [
        "CAACAgIAAxkBAAIBDmkYDreSSVSM6bynWvtC_TWgphZsAAJDTAACbJLASf1GsnTNQ9yENgQ",
        "CAACAgIAAxkBAAPsaRgLOe9cAAF13ptR8I7d_JxJmgABpAACsk8AAnQrwEncUrXf55SqxjYE",
        "CAACAgIAAxkBAAP5aRgLleZJqfHJuYEMuFbSe-qd3_UAAnxPAAKH_MBJERttDLsVVxA2BA",
        "CAACAgIAAxkBAAP3aRgLlfC3OdZ2AYHzF-IwrdK1eSYAArdLAAJHN8FJ9eprbxFAUYo2BA"
    ],
    
    # Добавление трека
    "add_track": [
        "CAACAgIAAxkBAAIBF2kYDxy11EHQ32k8I17JfEsT2gIaAAKxWAAC5UTBSW21kyn13Ph1NgQ",
        "CAACAgIAAxkBAAPjaRgKs04bj-8xDKNgfuJAEWeXvrsAA0gAAnqfwEmWDtAr5PwXUjYE",
        "CAACAgIAAxkBAAP7aRgMvEO0UTPPG0PxKVDexPCZy98AApVQAAJ4cMFJgqJ1IfE_lBg2BA"
    ],
    
    # Донат
    "donate": [
        "CAACAgIAAxkBAAPMaRgJJIKirCZImwABJoDSawirqx6CAALwTwACfFPASTIAAbSzn1OB9jYE",
        "CAACAgIAAxkBAAPyaRgLdYcsobhuxaLsikH2OovdhU4AAgZWAAKdLMFJFCYCXGJp8wc2BA",
        "CAACAgIAAxkBAAIBImkYD0_rKXV9OWfTepex_a5Zk17PAAKCUQACeJDASc3FV8lAi0F-NgQ"
    ],
    
    # Ошибки
    "error": [
        "CAACAgIAAxkBAAIBJGkYD2dA53FL4zWnwtb94-yarXc2AALTSAACmIzBSYz8MnSMUzK-NgQ",
        "CAACAgIAAxkBAAIBJmkYD2h4BqZqFKuZjNGUgJ9B7IQMAAL6SQAC_XHBSWs-i0RW10G5NgQ",
        "CAACAgIAAxkBAAIBKGkYD2-7Mx7NVOykF6agEDK_w5d2AAK-TAACCCjBST5RRfHZylSdNgQ",
        "CAACAgIAAxkBAAIBKWkYD3BMDZCuWlrLlK2aFNkBq93FAAKNSAACuTPASXZ0waLV-zFwNgQ"
    ],
    
    # Админка
    "admin": [
        "CAACAgIAAxkBAAM0aRc1BLgNs1wPyUeiKSYXlPFbJYQAAjxoAAKQColIe1-wGNCk1lU2BA",
        "CAACAgIAAxkBAAMqaRc0R6rZzc7vD_AKjZg58dL2oIgAAkJfAAIlHIhIvDNxfafaQPA2BA",
        "CAACAgIAAxkBAAM4aRc1Jc7MButl-0s7Orbu_NdLKSIAAkVcAALIiZFIuzkNsFQjqI02BA",
        "CAACAgIAAxkBAANnaRc7gxVGSynOMqSz6xbVAy4o4LcAAipgAAJb2YhI2iIirqGiN6A2BA",
        "CAACAgIAAxkBAANpaRc7k1LHuXmOsc603V9kwtCMCOMAAqteAAJ20pFI0r68y0RLq1M2BA"
    ],
    
    # Рандомные стикеры (для команды /random_sticker)
    "random_fun": [
        "CAACAgIAAxkBAANxaRc95oNnpnLYz80L8i6qe45xTwwAAk0AAwb1nCob6_ZZ0HW0fzYE",
        "CAACAgIAAxkBAANvaRc91-EwIB8YCYhnJCKMCg5OgkcAAo4NAAJnFxhJ5-rlMDLUsZo2BA",
        "CAACAgIAAxkBAAOYaRgGiZucLv11_pGGQqIr35AUUjUAAkJdAAKZLWlIVzlepWUXVPk2BA",
        "CAACAgIAAxkBAAOaaRgGlOrsB8FPTse2OXNsIz5Lj5cAAvCTAALQ6qhKmL9CzWM0Ss82BA",
        "CAACAgIAAxkBAAOcaRgGqRAfWOd9xD5h4DhS36JyXUQAArdtAAKUiEFKepDuraeiiEQ2BA",
        "CAACAgIAAxkBAAOeaRgGuoSzBQ7OUPpODt1y6WnChUMAAqowAAJM9vlJoDbc0MCj2E82BA",
        "CAACAgIAAxkBAAOgaRgGyXmTC6UhstqxNetG_z_U9QIAAmwtAALFiQABSo5-4b7_UJaNNgQ",
        "CAACAgIAAxkBAAOiaRgG1OT0XQGZyzSAI4L_aObKr0EAAkVcAALIiZFIuzkNsFQjqI02BA",
        "CAACAgIAAxkBAAOkaRgG7VFQlHvgDyrzH2ktgw6vF60AAkMAA4HQBBasmcO2Iuym8jYE",
        "CAACAgIAAxkBAAOmaRgG-822RhR9FQbuBkLy1Hmo8jsAAj1EAAJ4xfFIIM1eBaFCZEk2BA",
        "CAACAgIAAxkBAAOoaRgHAs6-VBbt0ZjXSfzF_-nwbkEAAjlFAAIHc8hJQX7JxVl8TwI2BA",
        "CAACAgIAAxkBAAOqaRgHC8Km_nvZsWkpKR-bBChCTuQAAnVOAAITKVFKQrwZsLf9zMw2BA",
        "CAACAgIAAxkBAAOsaRgHHLAvWHaheNdZ8OJgcHXxoRQAAmsAA4wS6xtJfhmD4QVexzYE",
        "CAACAgQAAxkBAAOuaRgHQ8eagnH1ZxRgFFaSeu2dl40AAjYOAAKfNDBRTYdxJr2sgbo2BA",
        "CAACAgIAAxkBAAOwaRgHS2RLWeJ1bK0hiiDXNdu_QLYAAicYAAKXeeFL1gEWEt7F3082BA",
        "CAACAgIAAxkBAAOyaRgHYBdc1CuI1YzikJVMkokULXgAAqwSAAJgkSBJ5892g53ANHw2BA",
        "CAACAgIAAxkBAAO0aRgHbHSM6GAJ6IMl6qXWPqJjjE8AAnQ4AAL7FIhKsnPoz2ZQXJ82BA",
        "CAACAgIAAxkBAAO2aRgHgUPSf58skFoli_TBHoZKRwgAAq4AAw1RbDhB48-pkDI4QTYE",
        "CAACAgIAAxkBAAO4aRgHjtaPXtxfbsdnbcf4Y9NvAcUAAk4NAAKoGYhLs1Snm17aqZ02BA",
        "CAACAgIAAxkBAAO6aRgHyPEbXgZ4GwM3_2f6qspFdG8AAjVZAAJP-DBK6UBev-6biMw2BA",
        "CAACAgIAAxkBAAO8aRgH17XE8FUC32xCLt5MGyt_vE8AAicAA9UIjTlSfaWu6duZsDYE",
        "CAACAgIAAxkBAAO-aRgH4xTq74LeuI4n0AWLusSMKNQAAgsLAALh36lKV9Na-yVtxAg2BA",
        "CAACAgIAAxkBAAPAaRgH6iW6aM0GpWm2is3Lm057vd0AAtsKAAJHp6hKTA_at98iW5I2BA",
        "CAACAgQAAxkBAAPCaRgH9Vlwz2Oly6vFL768m7MGJHsAAuMWAAJnGHlTt7m8KxzRWoA2BA",
        "CAACAgIAAxkBAAPEaRgH_Eq6uG9EncT76gtgZuyU8LgAAgQAAwb1nCrzWS2Gj8jbnTYE",
        "CAACAgIAAxkBAAPGaRgIDK2rNBbPHzrDVlYlmvUO0asAAlgjAAL_FHlIffE1VUvWUpY2BA",
        "CAACAgIAAxkBAAPIaRgIGW2C1o-Vlj291Iixr7mlYHYAArVfAAJOnlhIUhvr1AILC_42BA"
    ]
}